ALTER TABLE `KEYWORDS` 
ADD COLUMN `USER_ID` INT NULL DEFAULT NULL AFTER `DESCRIPTION`,
ADD INDEX `FK_USER_KEYWORDS_idx` (`USER_ID` ASC);
;
ALTER TABLE `KEYWORDS` 
ADD CONSTRAINT `FK_USER_KEYWORDS`
  FOREIGN KEY (`USER_ID`)
  REFERENCES `KEYWORDS` (`ID`)
  ON DELETE CASCADE
  ON UPDATE CASCADE;