ALTER TABLE `SIGNATURE` 
ADD COLUMN `START_DATE` DATETIME NULL DEFAULT NULL AFTER `FREQUENCY`,
ADD COLUMN `STATUS` VARCHAR(255) NULL DEFAULT NULL AFTER `START_DATE`,
ADD COLUMN `SEND_PUSH` INT NULL DEFAULT '0' AFTER `STATUS`,
ADD COLUMN `CURRENCY` VARCHAR(255) NULL DEFAULT NULL AFTER `SEND_PUSH`,
ADD COLUMN `ICON_IMAGE` VARCHAR(500) NULL DEFAULT NULL AFTER `CURRENCY`,
CHANGE COLUMN `FREQUENCY` `FREQUENCY` VARCHAR(255) NULL DEFAULT NULL ;
