CREATE TABLE `USERS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(500) NULL DEFAULT NULL,
  `EMAIL` VARCHAR(255) NULL DEFAULT NULL,
  `PASSWORD` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`));
