ALTER TABLE `SIGNATURE` 
ADD COLUMN `USER_ID` INT NULL DEFAULT NULL AFTER `ICON_IMAGE`,
ADD INDEX `FK_USER_SIGNATURE_idx` (`USER_ID` ASC);
;
ALTER TABLE `SIGNATURE` 
ADD CONSTRAINT `FK_USER_SIGNATURE`
  FOREIGN KEY (`USER_ID`)
  REFERENCES `USERS` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;