CREATE TABLE `SIGMA`.`signature_keywords` (
  `SIGNATURE_ID` INT NOT NULL,
  `KEYWORD_ID` INT NOT NULL,
  INDEX `FK_SK_SIGNATURE_ID_idx` (`SIGNATURE_ID` ASC),
  INDEX `FK_SK_KEYWORD_ID_idx` (`KEYWORD_ID` ASC),
  CONSTRAINT `FK_SK_SIGNATURE_ID`
    FOREIGN KEY (`SIGNATURE_ID`)
    REFERENCES `SIGMA`.`SIGNATURE` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_SK_KEYWORD_ID`
    FOREIGN KEY (`KEYWORD_ID`)
    REFERENCES `SIGMA`.`KEYWORDS` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);