ALTER TABLE `SIGNATURE_KEYWORDS` 
DROP FOREIGN KEY `FK_SK_KEYWORD_ID`;
ALTER TABLE `SIGNATURE_KEYWORDS` 
CHANGE COLUMN `KEYWORD_ID` `KEYWORDS_ID` INT NOT NULL ;
ALTER TABLE `SIGNATURE_KEYWORDS` 
ADD CONSTRAINT `FK_SK_KEYWORD_ID`
  FOREIGN KEY (`KEYWORDS_ID`)
  REFERENCES `KEYWORDS` (`ID`)
  ON DELETE CASCADE
  ON UPDATE CASCADE;